version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    restart: always
    user: root
    ports:
      - '8181:8080'
      - '50000:50000'
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - '/docker-data/jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/usr/local/bin/docker'
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    restart: always
    hostname: 'sisopsti.nemezes.xyz'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://sisopsti.mutantbr.com:8443'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['time_zone'] = 'America/Sao_Paulo'
    ports:
      - '8443:8443'
      - '2224:22'
    volumes:
      - '/docker-data/gitlab/config:/etc/gitlab'
      - '/docker-data/gitlab/logs:/var/log/gitlab'
      - '/docker-data/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - '/docker-data/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
